server:
  port: 80
   #context-path: /
   #session-timeout: 60
   #tomcat:
      #max-threads: 100
      #uri-encoding: UTF-8

spring:
    mvc:
       static-path-pattern: /**
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.5:3306/job?characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      druid:
         initial-size: 5
         max-active: 10

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
        naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #命名规则 org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy(大写下划线分割)
      properties:
        hibernate:
          #dialect: org.hibernate.dialect.MySQLDialectUTF8
          format_sql: true



logging:
  level:
    root: debug


